# -*- coding: utf-8 -*-
"""neural_networks_basics_01.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uMURKf4wwfgqewbwwRFtSxXltJ9c0zju

## Dataset
"""

print("hello world")

students = [ [2,7], [5,6], [8,5], [1,4] ]

target = [0, 1, 1, 0]

counter = 0
for student in students:
  counter+=1
  print(f"student {counter}= Study Hours: {student[0]}, Sleep Hours: {student[1]}")

"""## Neuron Formula"""

w1 = 0.5
w2 = 0.3
bias = 0.1

def neuron(x1, x2):
  z = w1*x1 + w2*x2 + bias
  return z;

neuron(2,7)

counter = 0
for student in students:
  counter += 1
  output = neuron(student[0], student[1])
  print(f"neuron value on student {counter}: {output}")

"""## Activation Functions

### 1. Sigmoid
"""

import math

def sigmoid(z):
  a = 1/(1 + math.exp(-z))
  return a

counter = 0
for student in students:
  counter += 1
  z = neuron(student[0], student[1])
  a = sigmoid(z)
  print(f"sigmoid applied student {counter}: {a}")

"""### 2. ReLu"""

def reLu(z):
  a = max(0, z)
  return a

counter = 0
for student in students:
  counter += 1
  z = neuron(student[0], student[1])
  a = reLu(z)
  print(f"reLu applied student {counter}: {a}")

"""### 3. Leaky ReLu"""

def leaky_reLu(z):
  if(z<0):
    a = 0.01*z;
  else:
    a = z;
  return a

counter = 0
for student in students:
  counter += 1
  z = neuron(student[0], student[1])
  a = leaky_reLu(z)
  print(f"leaky reLu applied student {counter}: {a}")

"""### 4. tanh

"""

import math

def tanh(z):
  a = ( math.exp(z) - math.exp(-z) ) / ( math.exp(z) + math.exp(-z) )
  return a

counter = 0
for student in students:
  counter += 1
  z = neuron(student[0], student[1])
  a = tanh(z)
  print(f"tanh applied student {counter}: {a}")

"""### 5. Softmax"""

import math
def softmax(z1, z2, z3, z4):
  a1 = math.exp(z1) / (math.exp(z1)+math.exp(z2)+math.exp(z3)+math.exp(z4))
  a2 = math.exp(z2) / (math.exp(z1)+math.exp(z2)+math.exp(z3)+math.exp(z4))
  a3 = math.exp(z3) / (math.exp(z1)+math.exp(z2)+math.exp(z3)+math.exp(z4))
  a4 = math.exp(z4) / (math.exp(z1)+math.exp(z2)+math.exp(z3)+math.exp(z4))
  return a1, a2, a3, a4

# Optimised solution 2
import math
def softmax(scores):
 exp_val = [math.exp(score) for score in scores] # 3.2 ---> [e^3.2, e^4.4, e^5.6, e^1.8]
 print(exp_val)
 final_val = [e / sum(exp_val) for e in exp_val]
 return final_val

"""### all students post activation function output values"""

output = []
z= []
for student in students:
  zi = neuron(student[0], student[1])
  z.append(zi)
  type1 = sigmoid(zi);
  type2 = reLu(zi);
  type3 = leaky_reLu(zi);
  type4 = tanh(zi);
  output.append([type1, type2, type3, type4])
# softmax does not apply on this example as we only need to predict pass or fail and not multiple output neurons needed
counter = 0
for output_data in output:
  counter += 1
  print(f"student {counter}: {output_data}")

"""## Graph Visualization"""

import matplotlib.pyplot as plt

import numpy as np

plt.plot([1,2,3,4],[1,4,9,16])  # x-axis: input, y-axis: output
plt.title("test: square graph")
plt.show()

z = []
for student in students:
  z.append( neuron(student[0], student[1]) )  # [z1, z2, z3, z4]
z.sort()
a_sigmoid = [sigmoid(i) for i in z]
a_reLu = [reLu(i) for i in z]
a_leaky_reLu = [leaky_reLu(i) for i in z]
a_tanh = [tanh(i) for i in z]

plt.plot(z,a_sigmoid)
plt.title("sigmoid graph")
plt.show()

plt.plot(z,a_reLu)
plt.title("reLu graph")
plt.show()

plt.plot(z,a_leaky_reLu)
plt.title("Leaky reLu graph")
plt.show()

plt.plot(z,a_tanh)
plt.title("tanh graph")
plt.show()

# Print all functions together in 1 graph
plt.plot(z,a_sigmoid, label="sigmoid", color="red")
plt.plot(z,a_reLu, label="reLu", color="blue")
plt.plot(z,a_leaky_reLu, label="leaky reLu", color="green", linestyle="--")
plt.plot(z,a_tanh, label="tanh", color="yellow", linewidth=4)

plt.legend(fontsize=10, loc="upper left")
plt.xlabel("z")
plt.ylabel("a")
plt.title("all activation functions")
plt.show()

