# -*- coding: utf-8 -*-
"""Forward_pass_and_numpy_03.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rTMu8SS5OL88qWgA-QNnJ32LJWYF9PHN

## Dataset
"""

w11 = 0.5   # input1 -> hidden neuron 1
w12 = 0.3   # input2 -> hidden1
w21 = 0.4   # input1 -> hidden2
w22 = 0.6   # input2 -> hidden2

b1 = 0.1    # bias for hidden1
b2 = 0.2    # bias for hidden2

w31 = 0.7   # hidden1 -> output
w32 = 0.5   # hidden2 -> output

b3 = 0.1    # bias for output

students = [ [2,7], [5,6], [8,5], [1,4] ]

targets = [0, 1, 1, 0]

names = ['A', 'B', 'C', 'D']

"""## Activation Functions

"""

import math
def sigmoid(z):
  a = 1 / (1+math.exp(-z))
  return a

def reLu(z):
  a = max(0, z)
  return a

"""## Forward Pass"""

def neuron(x1, x2, w1, w2, b):
  z = w1*x1 + w2*x2 + b;
  return z;

def forward_pass(x1, x2):
  z11 = neuron(x1, x2, w11, w12, b1)
  a11 = reLu(z11)
  z12 = neuron(x1, x2, w21, w22, b2)
  a12 = reLu(z12)
  z31 = neuron(a11, a12, w31, w32, b3)
  output = sigmoid(z31)
  return output

outputs = []
def calc_forward_pass(students):
  for student in students:
    outputs.append(forward_pass(student[0], student[1]))
  return outputs

calc_forward_pass(students)

"""## Loss

#### y^ (y_pred)-> prediction value
#### y -> target value

#### To handle edge cases:
####    epsilon = 1e-10
####    y_pred = max(epsilon, min(1-epsilon, y_pred)

#### 1. MSE - Regression:- Loss = (y^ - y)^2
#### 2. Cross Entropy (Binary) - Classification:- Loss = -( ylog y^ + (1-y)log(1-y^) )

#### if we do batch training, we take average of all calculated losses
"""

import math
for i in range(0, len(outputs)):
  y = targets[i]
  y_pred = outputs[i]
  epsilon = 1e-10
  new_y_pred = max(epsilon, min(1-epsilon, y_pred))
  loss = - ( y*math.log(new_y_pred) + (1-y)*math.log(1-new_y_pred) )
  print(loss)

"""## Using Numpy"""

import numpy as np

# A regular Python list
python_list = [1, 2, 3, 4, 5]

# A NumPy array (called "ndarray" -> N-dimensional array)
numpy_array = np.array([1, 2, 3, 4, 5])

print("Python list:", python_list)
print("NumPy array:", numpy_array)
print()

# THE MAGIC: NumPy lets you do math on entire arrays at once!
print("--- Python list math ---")
# This would NOT work: python_list * 2 gives [1,2,3,4,5,1,2,3,4,5]!
print("python_list * 2:", python_list * 2)   # repeats the list!

print("\n--- NumPy array math ---")
print("numpy_array * 2:", numpy_array * 2)   # multiplies each element by 2!
print("numpy_array + 10:", numpy_array + 10) # adds 10 to each!
print("numpy_array ** 2:", numpy_array ** 2) # squares each!

# Vectorization - when numpy does math on all elements of an array at once

# Inputs as a NumPy array
# if its a 1D array (1,2) it will automatically be written as (2,1)
# in 1D(output layer) - no transpose, if 2D(hidden layers) - transpose needed
x = np.array([5, 6])  # study=5, sleep=6 for Student B

# Weights for hidden layer (as a matrix)
# Each row = weights for one hidden neuron
W_hidden = np.array([
    [0.5, 0.3],   # weights for h1: [study_weight, sleep_weight]
    [0.4, 0.6]    # weights for h2: [study_weight, sleep_weight]
])

# Biases for hidden layer
b_hidden = np.array([0.1, 0.2])

# Forward pass for HIDDEN layer in ONE line!
# np.dot() does matrix multiplication
z_hidden = np.dot(W_hidden, x) + b_hidden

print("x (inputs):     ", x)
print("W_hidden:")
print(W_hidden)
print("b_hidden:       ", b_hidden)
print()
print("z_hidden (before activation):", z_hidden)

# Vectorized activation functions
def sigmoid_np(x):
    """Sigmoid that works on NumPy arrays"""
    return 1 / (1 + np.exp(-x))

def relu_np(x):
    """ReLU that works on NumPy arrays"""
    return np.maximum(0, x)   # np.maximum works element-by-element


def forward_pass_numpy(x):
    """Complete forward pass using NumPy"""

    # Hidden layer: W × x + b, then ReLU
    z_hidden = np.dot(W_hidden, x) + b_hidden
    print(f"z_hidden: {z_hidden}")
    h = relu_np(z_hidden)
    print(f"neuron value after activation: {h}")

    # Output layer: W × h + b, then Sigmoid
    z_output = np.dot(W_output, h) + b_output
    print(f"z_output: {z_output}")
    y_hat = sigmoid_np(z_output)
    print(f"output value after activation: {y_hat}")

    return y_hat


# Define output layer weights and bias as NumPy arrays
W_output = np.array([0.7, 0.5])   # weights from h1, h2 to output
b_output = 0.1                     # bias for output

# Test on Student B
x_b = np.array([5, 6])
y_hat_b = forward_pass_numpy(x_b)

print(f"Student B prediction (NumPy): {y_hat_b:.4f}")
print(f"Compare with loop version:    0.9977")
print(f"Match? {abs(y_hat_b - 0.9977) < 0.001}")

# Stack all students into a single matrix
# Each ROW = one student, each COLUMN = one feature
X = np.array([
    [2, 7],   # Student A
    [5, 6],   # Student B
    [8, 5],   # Student C
    [1, 4]    # Student D
])

# Targets as NumPy array
y = np.array([0, 1, 1, 0])

print("X (input matrix):")
print(X)
print(f"\nShape: {X.shape}  (4 students, 2 features each)")


# Forward pass for ALL students at once!
def forward_pass_batch(X):
    """Forward pass for multiple students in one go"""

    # Hidden layer
    # X @ W_hidden.T means: each row of X times W_hidden transposed
    # np.dot() is matrix multiplication of 2d array while @ handles all types of array matrix multiplication
    # .T means "transpose" (flip rows and columns)
    Z_hidden = X @ W_hidden.T + b_hidden
    print(f"Z_hidden: {Z_hidden}")
    H = relu_np(Z_hidden)
    print(f"\nH: {H}")

    # Output layer
    Z_output = H @ W_output + b_output
    print(f"\nZ_output: {Z_output}")
    # since 1D array, z_output will automatically be transposed
    print(f"z_output shape: {Z_output.shape}")
    y_hat = sigmoid_np(Z_output)
    print(f"y_hat: {y_hat}")

    return y_hat


# Get predictions for all 4 students AT THE SAME TIME!
predictions = forward_pass_batch(X)

print("\n--- ALL PREDICTIONS AT ONCE ---")
for i in range(len(students)):
    print(f"Student {names[i]}: prediction = {predictions[i]:.4f}, target = {y[i]}")

# Remember:- to make code consistent, and use transpose everywhere, we convert 1D arrays into 2D arrays

# in numpy, * is normal element wise multiplication - both arrays should have same shape
# @ is matrix multiplication - sum of all multiplicated values - shape:- (mXp) @ (pXn) = (mXn)

def cross_entropy(y, predictions):
  epsilon = 1e-10
  # predictions = np.maximum(epsilon, np.minimum(1-epsilon, predictions))
  # we cannot use above because epsilon is a single value and predictions is array therefore we use clip
  predictions = np.clip(predictions, epsilon, 1-epsilon)
  # since y and predictions have same shape, use normal element wise multiplication
  loss = - ( y * np.log(predictions) + (1-y) * np.log(1-predictions) )
  # doing batch training, therefore average of all losses calculated
  loss = np.mean(loss)
  return loss

cross_entropy(y, predictions)

