# -*- coding: utf-8 -*-
"""04,05,06_back_propagation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pjFovJ-U5dLbwlOYZH-aVDaWq4yGCfg7
"""

import numpy as np                    # for fast math
import matplotlib.pyplot as plt       # for plotting the loss curve

# Set a "seed" so random numbers are the same every time we run
# This makes our results reproducible (you'll get the same numbers as me!)
np.random.seed(42)

# Our student data
# Each row = [study_hours, sleep_hours]
X = np.array([
    [2, 7],   # Student A
    [5, 6],   # Student B
    [8, 5],   # Student C
    [1, 4]    # Student D
], dtype=float)

# The correct answers (0 = fail, 1 = pass)
# reshape(-1, 1) makes it a column: [[0], [1], [1], [0]]
y = np.array([[0], [1], [1], [0]], dtype=float)

print("Inputs X:")
print(X)
print("\nTargets y:")
print(y)
print(f"\nWe have {X.shape[0]} students, each with {X.shape[1]} features")

# Normalization: scale features so they have similar ranges
# We use "standardization": (value - mean) / standard_deviation
# This makes training much more stable!

# Why Normalize?
# Imagine measuring people's height (in cm, ~170) and weight (in kg, ~70).
# The height numbers are bigger, so the network might think height matters more — just because of the units!
# Normalizing makes all features have similar ranges (centered around 0, spread of 1).
# Now the network treats them fairly. This is a standard step in almost every ML project!

# axis=0 calculates values for each column separately while without it, a single value for the entire array calculated together
X_mean = X.mean(axis=0)
X_std = X.std(axis=0)
X_norm = (X - X_mean) / X_std

print("Original X:")
print(X)
print("\nNormalized X (now centered around 0):")
print(X_norm)
print(f"\nMean of each column now: {X_norm.mean(axis=0)}")  # should be ~0
print(f"Std of each column now: {X_norm.std(axis=0)}")      # should be ~1

X = X_norm

# Network structure: 2 inputs → 2 hidden neurons → 1 output

# Initialize weights with small RANDOM values
# We can't start at zero (we'll learn why in Module 9!) - dead neuron in case of weight as 0, also every neuron behaves same, therefore every weight unique
# randn gives random numbers from a normal distribution

# Weights for hidden layer: shape (2 hidden neurons, 2 inputs)
W_hidden = np.random.randn(2, 2) * 0.5

# Biases for hidden layer: shape (2,) - one per neuron, start at zero
b_hidden = np.zeros(2)

# Weights for output layer: shape (1 output, 2 hidden inputs)
W_output = np.random.randn(1, 2) * 0.5

# Bias for output: shape (1,)
b_output = np.zeros(1)

print("W_hidden (2 neurons, 2 weights each):")
print(W_hidden)
print(f"\nb_hidden: {b_hidden}")
print(f"\nW_output (1 neuron, 2 weights): {W_output}")
print(f"\nb_output: {b_output}")

# Count total parameters
total = W_hidden.size + b_hidden.size + W_output.size + b_output.size
print(f"\nTotal trainable parameters: {total}")

# Activation Functions

def reLu(Z):
  return np.maximum(0,Z)

def sigmoid(Z):
  return (1/(1+np.exp(-Z)))

def loss(y, y_pred):
  epsilon = 1e-10
  y_pred = np.clip(y_pred, epsilon, 1-epsilon)
  L = 0 - (y * np.log(y_pred) + (1-y) * np.log(1-y_pred))
  L = np.mean(L)
  return L

def loss_derivative(y, y_pred):
  m = X.shape[0]
  return (- y/y_pred + (1-y)/(1-y_pred))/m

def sigmoid_derivative(z):
  return sigmoid(z)*(1-sigmoid(z))

def reLu_derivative(z):
  return (z>0).astype(float)

def z_derivative_via_w_or_a(i):
  return i;

def z_derivative_via_b():
  return 1;

def forward_pass():
  Z_hidden = X @ W_hidden.T + b_hidden
  a = reLu(Z_hidden)

  Z_output = a @ W_output.T + b_output
  y_pred = sigmoid(Z_output)

  L = loss(y, y_pred)
  return (Z_hidden, a, Z_output, y_pred, L)

Z_hidden, a, Z_output, y_pred, L = forward_pass()
print("W_hidden:")
print(W_hidden)
print("\nb_hidden:")
print(b_hidden)
print("\nW_output:")
print(W_output)
print("\nb_output:")
print(b_output)
print("\nZ_hidden:")
print(Z_hidden)
print("\na:")
print(a)
print("\nZ_output:")
print(Z_output)
print("\ny_pred:")
print(y_pred)
print("\nLoss:")
print(L)

learning_rate = 0.01

def back_propagation(X, y, y_pred, Z_output, a):
  dL_dy_pred = loss_derivative(y, y_pred)
  dy_pred_dz_output = sigmoid_derivative(Z_output)
  dz_output_dw_output = z_derivative_via_w_or_a(a)

  # w jha aata hai, vha transpose krna hota h
  # (4,1)*(4,1) and then its output is (4,1) and we have dz_output_dw_output as (4,2) therefore (4,1).T @ (4,2) = (1,2)
  delta_ouput = dL_dy_pred * dy_pred_dz_output # (4,1) output
  dL_dw_output = delta_ouput.T @ dz_output_dw_output # (1,2) output
  new_W_output = W_output - learning_rate * dL_dw_output

  # now for new_W_hidden
  # dL_dy_pred (4,1) * dy_pred_dz_output (4,1) which becomes delta_output (4,1)
  dz_output_da = z_derivative_via_w_or_a(W_output) # (1,2)
  da_dz_hidden = reLu_derivative(Z_hidden) # (4,2)

  dz_hidden_dw_hidden = z_derivative_via_w_or_a(X) # (4,2)

  delta_temp = delta_ouput @ dz_output_da # (4,1) @ (1,2) = (4,2)
  delta_hidden = delta_temp * da_dz_hidden # (4,2) * (4,2) = (4,2)
  dL_dw_hidden = dz_hidden_dw_hidden.T @ delta_hidden  # (4,2).T @ (4,2) = (2,2)
  new_W_hidden = W_hidden - learning_rate * dL_dw_hidden

  print("new_W_output:")
  print(new_W_output)
  print("\nnew_w_hidden:")
  print(new_W_hidden)

back_propagation(X, y, y_pred, Z_output, a)

# AI

import numpy as np
import matplotlib.pyplot as plt
np.random.seed(42)

# ---------- DATA ----------
X = np.array([[2,7],[5,6],[8,5],[1,4]], dtype=float)  # (4,2) students × features
y = np.array([[0],[1],[1],[0]], dtype=float)          # (4,1) targets

# ---------- NORMALIZE ----------
# axis=0 → per column (per feature). Centers data around 0, spread 1.
X_mean = X.mean(axis=0)
X_std = X.std(axis=0)
X = (X - X_mean) / X_std

# ---------- INIT WEIGHTS ----------
# Small RANDOM (not zero → break symmetry so each neuron learns differently)
W_hidden = np.random.randn(2, 2) * 0.5   # (2 neurons, 2 inputs)
b_hidden = np.zeros(2)                     # (2,)
W_output = np.random.randn(1, 2) * 0.5   # (1 neuron, 2 inputs)
b_output = np.zeros(1)                     # (1,)

# ---------- ACTIVATIONS ----------
def reLu(Z): return np.maximum(0, Z)
def sigmoid(Z): return 1/(1 + np.exp(-Z))

# ---------- LOSS ----------
def loss(y, y_pred):
    epsilon = 1e-10
    y_pred = np.clip(y_pred, epsilon, 1-epsilon)   # avoid log(0)
    return np.mean(-(y*np.log(y_pred) + (1-y)*np.log(1-y_pred)))

# ---------- DERIVATIVES (brute force, kept separate!) ----------
def loss_derivative(y, y_pred):
    m = X.shape[0]
    return (-y/y_pred + (1-y)/(1-y_pred)) / m   # dL/dy_pred (averaged)

def sigmoid_derivative(z):
    return sigmoid(z) * (1 - sigmoid(z))        # dy_pred/dz_out

def reLu_derivative(z):
    return (z > 0).astype(float)                # da/dz_hidden

def z_derivative_via_w_or_a(i):
    return i      # dz/dw = input,  dz/da = weight

def z_derivative_via_b():
    return 1      # dz/db = 1

# ---------- FORWARD ----------
def forward_pass():
    Z_hidden = X @ W_hidden.T + b_hidden    # (4,2)@(2,2)+(2,) = (4,2)
    a = reLu(Z_hidden)                        # (4,2)
    Z_output = a @ W_output.T + b_output      # (4,2)@(2,1)+(1,) = (4,1)
    y_pred = sigmoid(Z_output)                # (4,1)
    L = loss(y, y_pred)
    return Z_hidden, a, Z_output, y_pred, L

Z_hidden, a, Z_output, y_pred, L = forward_pass()
print("y_pred:\n", np.round(y_pred, 4))
print("Loss:", round(L, 4))

# ---------- BACKWARD (brute force) ----------
learning_rate = 0.5

def back_propagation(X, y, y_pred, Z_output, a, Z_hidden):
    global W_hidden, b_hidden, W_output, b_output

    # === OUTPUT LAYER ===
    dL_dy_pred = loss_derivative(y, y_pred)          # (4,1)
    dy_pred_dz_output = sigmoid_derivative(Z_output) # (4,1)
    # combine along chain → element-wise (same shape, per student)
    delta_output = dL_dy_pred * dy_pred_dz_output    # (4,1)

    dz_output_dw_output = z_derivative_via_w_or_a(a) # = a, (4,2)
    # gradient = delta × input, SUMMED over students → transpose!
    # (1,4) @ (4,2) = (1,2)  [students summed away]
    dL_dw_output = delta_output.T @ dz_output_dw_output   # (1,2)
    dL_db_output = np.sum(delta_output, axis=0)            # (1,)

    # === HIDDEN LAYER ===
    dz_output_da = z_derivative_via_w_or_a(W_output) # = W_output, (1,2)
    # spread error back through output weights → dot product (shapes match, no .T)
    # (4,1) @ (1,2) = (4,2)
    delta_temp = delta_output @ dz_output_da         # (4,2)

    da_dz_hidden = reLu_derivative(Z_hidden)         # (4,2)
    # gate the error → element-wise (same shape)
    delta_hidden = delta_temp * da_dz_hidden         # (4,2)

    dz_hidden_dw_hidden = z_derivative_via_w_or_a(X) # = X, (4,2)
    # gradient = delta × input, SUMMED over students → transpose!
    # (2,4) @ (4,2) = (2,2)
    dL_dw_hidden = dz_hidden_dw_hidden.T @ delta_hidden  # (2,2)
    dL_db_hidden = np.sum(delta_hidden, axis=0)          # (2,)

    # === UPDATE ALL PARAMETERS ===
    W_output = W_output - learning_rate * dL_dw_output
    b_output = b_output - learning_rate * dL_db_output
    W_hidden = W_hidden - learning_rate * dL_dw_hidden
    b_hidden = b_hidden - learning_rate * dL_db_hidden

back_propagation(X, y, y_pred, Z_output, a, Z_hidden)
print("\nAfter one step:")
_, _, _, y_pred_new, L_new = forward_pass()
print("New loss:", round(L_new, 4), "(was", round(L, 4), ")")

# Re-initialize for a clean run
np.random.seed(42)
W_hidden = np.random.randn(2, 2) * 0.5
b_hidden = np.zeros(2)
W_output = np.random.randn(1, 2) * 0.5
b_output = np.zeros(1)

learning_rate = 0.5
epochs = 1000
loss_history = []

for epoch in range(epochs):
    # 1. FORWARD
    Z_hidden, a, Z_output, y_pred, L = forward_pass()
    loss_history.append(L)

    # 2. BACKWARD (updates all weights & biases)
    back_propagation(X, y, y_pred, Z_output, a, Z_hidden)

    if epoch % 100 == 0:
        print(f"Epoch {epoch:4d} | Loss: {L:.4f}")

print(f"\nFinal loss: {loss_history[-1]:.4f}")

# Plot the learning curve
plt.figure(figsize=(10,6))
plt.plot(loss_history, color='blue', linewidth=2)
plt.title("Training Loss Over Time")
plt.xlabel("Epoch"); plt.ylabel("Loss")
plt.grid(True, alpha=0.3)
plt.show()

# Check final accuracy
_, _, _, final_pred, _ = forward_pass()
names = ['A','B','C','D']
correct = 0
for i in range(len(X)):
    rounded = 1 if final_pred[i][0] >= 0.5 else 0
    if rounded == int(y[i][0]): correct += 1
    print(f"Student {names[i]}: pred={final_pred[i][0]:.4f} -> {rounded} (target {int(y[i][0])})")
print(f"Accuracy: {correct}/{len(X)} = {100*correct/len(X):.0f}%")

